core/accounts/urls.py
from django.urls import path
from .views import LoginView, LogoutView, SignUpView, ProfileView

app_name = 'accounts'
urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'), 
    path('signup/', SignUpView.as_view(), name='signup'),
    path('profile/', ProfileView.as_view(), name='profile'),
]

core/blog/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import BlogPostList, BlogPostCreate, BlogPostDetail, CommentCreateView, EditPostView

urlpatterns = [
    path('about/', TemplateView.as_view(template_name="blog/about.html"), name='about-page'),
    
    path('posts/', BlogPostList.as_view(), name='posts-list'),
    path('detail/<int:pk>/comment-create/', CommentCreateView.as_view(), name='comment_create'),
    
    path('edit/<int:pk>/', EditPostView.as_view(), name='edit-post'),
    path('create/', BlogPostCreate.as_view(), name='create-post'),
    path('detail/<int:pk>/', BlogPostDetail.as_view(), name='post-detail'),
    # create read update delete 
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('accounts/', include('accounts.urls')), 
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include('blog.api.v1.urls')),
    
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/templates/Base.html
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock title %}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
        }
        
        .navbar {
            background-color: #333;
            color: #fff;
            padding: 10px;
            display: flex; 
            justify-content: space-between;
        }
        
        .navbar ul {
            list-style-type: none;
            margin: 0;
            padding: 0;
            overflow: hidden;
        }
        
        .navbar li {
            float: left;
        }
        
        .navbar li a {
            display: block;
            color: #fff;
            text-align: center;
            padding: 14px 16px;
            text-decoration: none;
            transition: background-color 0.3s;
        }
        
        .navbar li a:hover {
            background-color: #555;
        }
        

        .navbar .auth-items {
            display: flex; /* Added flex display */
        }
        
        .navbar .auth-items li {
            margin-left: 10px; /* Added margin for spacing between items */
        }
        
        .content {
            margin-top: 20px;
            padding: 20px;
            background-color: #f7f7f7;
            border-radius: 5px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }
        
        .content h1 {
            color: #333;
            margin-bottom: 10px;
        }
        
        .content p {
            color: #555;
        }
    </style>
</head>
<body>
    <div class="navbar">
        <ul>
            <li><a href="{% url 'about-page' %}">About</a></li>
            <li><a href="{% url 'posts-list' %}">Home</a></li>
            <li><a href="{% url 'create-post' %}">Create</a></li>
        </ul>

        <ul class="auth-items">
            
            {% if request.user.is_authenticated %}
                
                <li><a href="{% url 'accounts:logout' %}">Log out</a></li>
                <li><a href="{% url 'accounts:profile' %}">profile</a></li>
                
            {%else%}
                <li><a href="{% url 'accounts:login' %}">Login</a></li>
                <li><a href="{% url 'accounts:signup' %}">Sign Up</a></li>
            {% endif %}
        </ul>
    </div>

    <div class="content">
        {% block body %}

        {% endblock %}
    </div>
</body>
</html>