core/blog/api/v1/urls.py
from django.urls import path
from .views import BlogPostListApiView, GetBlogPostApiView

app_name = 'api'

urlpatterns = [
    path('post-list/', BlogPostListApiView.as_view(), name="post-list"),
    path('post-detail/<int:pk>/', GetBlogPostApiView.as_view(), name="post-detail"),
]

core/blog/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import BlogPostList, BlogPostCreate, BlogPostDetail, CommentCreateView, EditPostView

urlpatterns = [
    path('about/', TemplateView.as_view(template_name="blog/about.html"), name='about-page'),
    
    path('posts/', BlogPostList.as_view(), name='posts-list'),
    path('detail/<int:pk>/comment-create/', CommentCreateView.as_view(), name='comment_create'),
    
    path('edit/<int:pk>/', EditPostView.as_view(), name='edit-post'),
    path('create/', BlogPostCreate.as_view(), name='create-post'),
    path('detail/<int:pk>/', BlogPostDetail.as_view(), name='post-detail'),
    # create read update delete 
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('accounts/', include('accounts.urls')), 
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include('blog.api.v1.urls')),
    
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.query import QuerySet
from django.urls import reverse
# CrEaTe YoUr MoDeLd HeRe ................


class IsActiveManager(models.Manager):
    def get_queryset(self) -> QuerySet:
        return super().get_queryset()


class CommentModel(models.Model):
    blog = models.ForeignKey('BlogPostModel', on_delete=models.CASCADE)
    content = models.TextField()
    created_time = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="Comments")
    spoiler = models.BooleanField(default=False)
    
    


class BlogPostModel(models.Model):
    DRAFT = 1
    POSTED = 2
    states = (
        (DRAFT, "draft"),
        (POSTED, "posted"),
    )
    author = models.ForeignKey(User, on_delete=models.PROTECT, related_name='blog_posts')
    content = models.TextField()
    # TODO: add support for content 
    state = models.PositiveSmallIntegerField(choices=states, default=DRAFT)
    created_date = models.DateTimeField(auto_now_add=True)
    modify_date = models.DateTimeField(auto_now=True)
    likes = models.IntegerField(default=0)
    comments = models.ManyToManyField(CommentModel, related_name="blog_comments", blank=True)
    title = models.CharField(max_length=35, unique=True)
    image = models.ImageField(upload_to='images', null=True, blank=True)


    
    
    objects = IsActiveManager()
    default_manager = models.Manager()

        
    def __str__(self):
        return str(self.title)
    
    def get_abs_api_url(self):
        return reverse("api:post-detail", args=[self.pk])

    def snippet(self):
        return self.content[:30]

core/blog/forms.py
from django import forms
from .models import CommentModel, BlogPostModel


class BlogPostForm(forms.ModelForm):
    class Meta:
        model = BlogPostModel
        fields = ('title', 'content', 'state', 'image')
        

class CommentForm(forms.ModelForm):
    class Meta:
        model = CommentModel
        fields = ('content',)

core/blog/api/v1/views.py
from rest_framework.views import Response
from rest_framework.generics import ListAPIView, ListCreateAPIView, RetrieveUpdateDestroyAPIView
from rest_framework.permissions import IsAuthenticatedOrReadOnly, IsAuthenticated
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework.filters import SearchFilter, OrderingFilter
from blog.models import BlogPostModel
from .serializer import BlogPostSerializer
from .pagination import BlogPaginator


class BlogPostListApiView(ListCreateAPIView):
    queryset = BlogPostModel.objects.all()
    serializer_class = BlogPostSerializer
    permission_classes = (IsAuthenticatedOrReadOnly, )
    pagination_class = BlogPaginator
    filter_backends = (DjangoFilterBackend, SearchFilter, OrderingFilter)
    filterset_fields = ('state', )
    search_fields = ('author__username', 'title')
    ordering_fields = ('created_date', 'modify_date')
    
    # filter_queryset = BlogPostModel.objects.aggregate(
class GetBlogPostApiView(RetrieveUpdateDestroyAPIView):
    queryset = BlogPostModel.objects
    serializer_class = BlogPostSerializer
    permission_classes = (IsAuthenticated, )

    

    

core/blog/views.py
from typing import Any
from django import http
from django.db import models
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic import ListView, FormView, DetailView, View, UpdateView
from django.urls import reverse_lazy
from .models import BlogPostModel, CommentModel
from .forms import BlogPostForm, CommentForm
from django.core.exceptions import ValidationError
from datetime import datetime


# CrEaTe YoUr ViEeS HeRe .


class BlogPostList(ListView):
    queryset = BlogPostModel.objects.filter(state=2)
    template_name = 'blog/blog_post_list.html'
    context_object_name  = 'posts'
    
    
class BlogPostCreate(FormView):
    
    form_class = BlogPostForm
    success_url = reverse_lazy('posts-list')
    template_name = 'blog/blog_post_create.html'

    @method_decorator(login_required(login_url="login"))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)
    
    
    
    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.author = self.request.user
        instance.save()
        return super().form_valid(form)
    

class BlogPostDetail(DetailView):
    model = BlogPostModel
    template_name = 'blog/blog_post_detail.html'
    context_object_name = 'post'
    
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comment_form'] = CommentForm()
        context['comments'] = CommentModel.objects.filter(blog=self.object)
        return context

class CommentCreateView(View):
    
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)
    
    def post(self, request, *args, **kwargs):
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.user = self.request.user
            comment.blog = BlogPostModel.objects.get(pk=self.kwargs['pk'])
            comment.save()
        return redirect('posts-list')

class EditPostView(UpdateView):
    model = BlogPostModel
    fields = ('title', 'content', 'state', 'image')
    success_url = reverse_lazy("posts-list")
    template_name = 'blog/update_post.html'
    context_object_name = 'post'
    
    def dispatch(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse:
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    
    def get(self, request, *args, **kwargs):
        if request.user == self.object.author:
            return super().get(request, *args, **kwargs)
        else:raise ValidationError("user is not owner of blog post")
        
    def post(self, request: HttpRequest, *args: str, **kwargs: Any) -> HttpResponse:
        self.form = BlogPostForm(request.POST, self.model)
        self.modify_date = datetime.now()
        # self.form.is_valid()
        # self.form.save()
        
        return super().post(request, *args, **kwargs)

core/templates/blog/about.html
{% extends 'Base.html' %}
{% block title %}About{% endblock title %}
{% block body %}
    <h1> About page </h1>
    <p> {% lorem 3 b random %}</p>
    <h2> more information </h2>
    <p> {% lorem 4 b random %}</p>


{% endblock body %}

core/templates/blog/blog_post_create.html
{% extends 'Base.html' %}
{% block title %}Post List{% endblock title %}
{% block body %}

<head>
    <style>
        /* CSS Styles */
        body {
            font-family: Arial, sans-serif;
        }
        .container {
            max-width: 500px;
            margin: 0 auto;
        }
        .form-group {
            margin-bottom: 20px;
        }
        .form-group label {
            display: block;
            font-weight: bold;
        }
        .form-group input[type="text"],
        .form-group textarea {
            width: 100%;
            padding: 10px;
            font-size: 16px;
            border: 1px solid #ccc;
            border-radius: 4px;
        }
        .form-group textarea {
            height: 200px;
        }
        .form-group input[type="submit"] {
            padding: 10px 20px;
            font-size: 16px;
            background-color: #4CAF50;
            color: white;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }
        #id_state{
            
                
            height: 30px;
            width: 200px;
            padding: 5px;
            border: 1px solid #ccc;
                  
                 
            font-family: Arial, sans-serif;
            font-size: 14px;
            background-color: #fff;
        }
        #id_image {
            color: red;
            
            margin-top: 10px;
            display: block;
            margin-bottom: 5px;
            font-weight: bold;
            font-family: Arial, sans-serif;
            font-size: 14px;
            background-color: #fff;
        }

    </style>
</head>
<body>
    <div class="container">
        <h1>Add Blog Post</h1>
        <form method="post">
            {% csrf_token %}

            <div class="form-group">
                <label for="id_title">Title:</label> <input type="text" name="title" maxlength="35" required id="id_title">

            </div> 
            <div class="form-group">
                <label for="id_content">Content:</label> 
                {{form.content}}
                <label for="id_state">State:</label> <select name="state" id="id_state">
                    <option value="1" selected>draft</option>
                    <option value="2">posted</option>
            </div>

            <div class="form-group">
                <label for="id_image">Image:</label> <input type="file" name="image" accept="image/*" id="id_image">
            </div>
            <div class="form-group">
                <input type="submit" value="Add Post">
            </div>
        </form>
    </div>

</body>

{% endblock body %}

core/templates/blog/blog_post_detail.html
{% extends 'base.html' %}

{% block body %}
    <h1>title : {{post.title}}</h1>
    <h2>athor : {{post.author}}</h2>
    <p>{{post.content}}</p>

  

    
<p> {{ i.image }}</p>


  <h3>Comments</h3>
  <ul>
    {% for comment in comments %}
      <li>{{ comment.user }}: {{ comment.content }}</li>
    {% endfor %}
  </ul>

  <!-- Comment form -->
  <h3>Add Comment</h3>
  <form method="post" action="{% url 'comment_create' post.id %}">
    {% csrf_token %}
    {{ comment_form.as_p }}
    <button type="submit">Add Comment</button>
  </form>
{% endblock %}

core/templates/blog/blog_post_list.html
{% extends 'Base.html' %}
{% block title %}Post List{% endblock title %}
{% block body %}
{% load blog_extras %}
<head>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
            background-color: #f9f9f9;
        }

        h1 {
            color: #333;
            text-align: center;
            margin-bottom: 30px;
        }

        .post {
            margin-bottom: 20px;
            padding: 20px;
            border: 1px solid #ccc;
            background-color: #fff;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
            border-radius: 4px;
        }

        .post h2 {
            margin-top: 0;
            color: #333;
            font-size: 24px;
            margin-bottom: 10px;
        }

        .post p {
            margin-bottom: 0;
            color: #666;
            font-size: 16px;
        }

        .no-posts {
            text-align: center;
            color: #999;
            font-size: 18px;
            margin-top: 50px;
        }
        #add-buttom {
            display: inline-block;
            padding: 10px 20px;
            background-color: #4CAF50;
            color: #fff;
            text-decoration: none;
            border-radius: 4px;
            font-size: 16px;
            border: none;
            cursor: pointer;
          }
        
          .button-link:hover {
            background-color: #45a049;
          }
    </style>
</head>
<body>
    <h1>Post List</h1>
    {% if posts %}
        {% for i in posts %}
        <div class="post">
            
            <h2><a href='/blog/detail/{{ i.pk }}/'>{{i.title|title}}</a></h2>
            <p>snippet : {{i.content|snippet}}</p>
            <p>created : {{ i.created_date }}</p>
            <p>modified : {{ i.modify_date }}</p>

        </div>
        {% endfor %}
        
        <a href=" {% url 'create-post' %}">
            <button id="add-buttom">Add your movie</button>
          </a>


    {% else %}
    <p class="no-posts">No posts available.</p>
    {% endif %}
</body>
    {% comment %} {% for i in posts %}
        
    {% endfor %}


</body> {% endcomment %}
{% endblock body %}

core/templates/blog/update_post.html
{% extends 'Base.html' %}
{%block title%} Update Post{%endblock%}
{% block body %}




    <h1>{{post.title}}</h1>
    <h2>author : {{post.author}}</h2>
    <h3> Edit </h3>
    <form method="post" action=''>
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Edit" />
    </form> 



{% endblock body %}